dataset:
  type: CNNDailymailDataset
  parameters:
    dataset_root: ./output/cnn_dailymail
    batch_size: 512

model_wrapper:
  type: MistralInstruct
  parameters:
    model_path: hf://ministral/Ministral-3b-instruct
optimizers:
  - type: GPTQSparseGPTOptimizer
    parameters:
      compiled_model_path: ./output/ministral-3b-sparsegptq-4bit
      group_size: 64
      seqlen: 512
      calibration_samples: 8
runtime:
  type: VLLMRuntime
  parameters:
    save_model_path: ./output/ministral-3b-sparsegptq-4bit
    max_tokens: 64
    batch_size: 512
    max_model_len: 64
    sparse_gptq_kernel: true
