model_wrapper:
  type: kenning.modelwrappers.object_detection.yolo_transfer_learning.YOLOV4TL
  parameters:
    model_path: kenning:///models/object_detection/yolov4.pth
    model_name: yolov4
    batch_size: 1
dataset:
  type: kenning.datasets.coco_dataset.COCODataset2017
  parameters:
    dataset_root: ./build/COCODataset2017
    dataset_type: val2017
    image_width: 608
    image_height: 608
optimizers:
  - type: kenning.optimizers.nni_pruning.NNIPruningOptimizer
    parameters:
      model_framework: torch
      pruner_type: mean_rank
      config_list:
          - sparsity_per_layer: 0.1
            op_types:
              - Conv2d
          - exclude: true
            op_partial_names:
              # Neck
              - neek.conv1.conv.0
              - neek.conv1.conv.1
              - neek.conv2.conv.0
              - neek.conv2.conv.1
              - neek.conv3.conv.0
              - neek.conv3.conv.1
              - neek.conv4.conv.0
              - neek.conv4.conv.1
              - neek.conv5.conv.0
              - neek.conv5.conv.1
              - neek.conv6.conv.0
              - neek.conv6.conv.1
              - neek.conv7.conv.0
              - neek.conv7.conv.1
              - neek.conv8.conv.0
              - neek.conv8.conv.1
              - neek.conv9.conv.0
              - neek.conv9.conv.1
              - neek.conv10.conv.0
              - neek.conv10.conv.1
              - neek.conv11.conv.0
              - neek.conv11.conv.1
              - neek.conv12.conv.0
              - neek.conv12.conv.1
              - neek.conv13.conv.0
              - neek.conv13.conv.1
              - neek.conv14.conv.0
              - neek.conv14.conv.1
              - neek.conv15.conv.0
              - neek.conv15.conv.1
              - neek.conv16.conv.0
              - neek.conv16.conv.1
              - neek.conv17.conv.0
              - neek.conv17.conv.1
              - neek.conv18.conv.0
              - neek.conv18.conv.1
              - neek.conv19.conv.0
              - neek.conv19.conv.1
              - neek.conv20.conv.0
              - neek.conv20.conv.1

              # Head
              - head.conv1.conv.0
              - head.conv1.conv.1
              - head.conv2.conv.0
              - head.conv3.conv.0
              - head.conv3.conv.1
              - head.conv4.conv.0
              - head.conv4.conv.1
              - head.conv5.conv.0
              - head.conv5.conv.1
              - head.conv6.conv.0
              - head.conv6.conv.1
              - head.conv7.conv.0
              - head.conv7.conv.1
              - head.conv8.conv.0
              - head.conv8.conv.1
              - head.conv9.conv.0
              - head.conv9.conv.1
              - head.conv10.conv.0
              - head.conv11.conv.0
              - head.conv11.conv.1
              - head.conv12.conv.0
              - head.conv12.conv.1
              - head.conv13.conv.0
              - head.conv13.conv.1
              - head.conv14.conv.0
              - head.conv14.conv.1
              - head.conv15.conv.0
              - head.conv15.conv.1
              - head.conv16.conv.0
              - head.conv16.conv.1
              - head.conv17.conv.0
              - head.conv17.conv.1
              - head.conv18.conv.0
      training_steps: 256
      activation: relu6
      compiled_model_path: ./build/model-yolo.pth
      mode: dependency_aware
      finetuning_epochs: 1
      finetuning_batch_size: 2
      confidence: 2
      criterion: kenning.utils.yolov4_loss.YOLOv4Loss
      optimizer: torch.optim.SGD
      pruning_on_cuda: true
      finetuning_learning_rate: 0.0001
      exclude_last_layer: true
runtime:
  type: kenning.runtimes.pytorch.PyTorchRuntime
  parameters:
    save_model_path: ./build/model-yolo.pth
report:
  type: MarkdownReport
  parameters:
    measurements: ./build/yolov4_pytorch_pruning.json
    report_path: ./build/yolov4_pytorch
