model_wrapper:
  type: kenning.modelwrappers.object_detection.yolo_transfer_learning.YOLOV4TL
  parameters:
    model_path: ./build/yolov4-openimages.pth
    model_name: yolov4-openimages
    classes: ./build/oid_classes
    batch_size: 1
    learning_rate: 0.001
    num_epochs: 10
    logdir: build/logs
dataset:
  type: kenning.datasets.open_images_dataset.OpenImagesDatasetV6
  parameters:
    dataset_root: ./build/OpenImagesDatasetV6
    task: object_detection
    classes: ./build/oid_classes
    image_width: 608
    image_height: 608
optimizers:
  # - type: kenning.optimizers.nni_pruning.NNIPruningOptimizer
  #   parameters:
  #     model_framework: torch
  #     pruner_type: apoz
  #     config_list:
  #       - sparsity_per_layer: 0.1
  #         op_types:
  #           - Conv2d
  #           - Linear
  #       - exclude: true
  #         op_names:
  #           - Conv_393
  #           - Conv_611
  #           - Conv_829
  #     training_steps: 256
  #     activation: relu6
  #     compiled_model_path: ./build/yolov4-pruned.pth
  #     mode: dependency_aware
  #     finetuning_epochs: 1
  #     finetuning_batch_size: 1
  #     confidence: 2
  #     criterion: kenning.utils.yolov4_loss.YOLOv4Loss
  #     optimizer: torch.optim.SGD
  #     pruning_on_cuda: false
  #     finetuning_learning_rate: 0.0001
  #     exclude_last_layer: false
  - type: kenning.optimizers.tflite.TFLiteCompiler
    parameters:
      target: int8
      compiled_model_path: ./build/int8.tflite
      inference_input_type: int8
      inference_output_type: int8
  - type: kenning.optimizers.tvm.TVMCompiler
    parameters:
      target: llvm -mcpu=core-avx2
      use_fp16_precision: true
      opt_level: 3
      conv2d_data_layout: NCHW
      conv2d_kernel_layout: OIHW
      compiled_model_path: ./build/int8_tvm.tar
runtime:
  type: TVMRuntime
  parameters:
    save_model_path: ./build/int8_tvm.tar