model_wrapper:
  type: kenning.modelwrappers.object_detection.yolo_transfer_learning.YOLOV4TL
  parameters:
    model_path: kenning:///models/object_detection/yolov4.pth
    model_name: yolov4
    batch_size: 1
dataset:
  type: kenning.datasets.coco_dataset.COCODataset2017
  parameters:
    dataset_root: ./build/COCODataset2017
    dataset_type: val2017
    image_width: 608
    image_height: 608
optimizers:
  - type: kenning.optimizers.tflite.TFLiteCompiler
    parameters:
      target: default
      compiled_model_path: ./build/int8.tflite
      inference_input_type: int8
      inference_output_type: int8
  - type: kenning.optimizers.tvm.TVMCompiler
    parameters:
      target: llvm -mcpu=core-avx2
      opt_level: 3
      compiled_model_path: ./build/int8_tvm.tar
      conv2d_data_layout: NCHW
      conv2d_kernel_layout: OIHW
runtime:
  type: TVMRuntime
  parameters:
    save_model_path: ./build/int8_tvm.tar
report:
  type: MarkdownReport
  parameters:
    measurements: ./build/yolov4_pytorch_int8.json
    report_path: ./build/yolov4_pytorch