model_wrapper:
  type: kenning.modelwrappers.object_detection.yolo_transfer_learning.YOLOV4TL
  parameters:
    model_path: kenning:///models/object_detection/yolov4.pth
    model_name: yolov4
    # if this is set to true the wrapper will download pre-trained weights
    reset_last_layers: true
    # classes: ./build/oid_classes
    backbone_layers_to_freeze:
      - down[1-5]
    batch_size: 1
    learning_rate: 0.001
    head_num_epochs: 3
    full_num_epochs: 10
    logdir: build/logs
dataset:
  # type: kenning.datasets.open_images_dataset.OpenImagesDatasetV6
  # parameters:
  #   dataset_root: ./build/OpenImagesDatasetV6
  #   task: object_detection
  #   classes: ./build/oid_classes
  #   image_width: 608
  #   image_height: 608
  type: kenning.datasets.coco_dataset.COCODataset2017
  parameters:
    dataset_root: ./build/COCODataset2017
    dataset_type: val2017
    image_width: 608
    image_height: 608
optimizers:
  - type: kenning.optimizers.tvm.TVMCompiler
    parameters:
      target: llvm
      opt_level: 3
      compiled_model_path: ./build/yolo_tvm.tar
runtime:
  type: kenning.runtimes.tvm.TVMRuntime
  parameters:
    save_model_path: ./build/yolo_tvm.tar
    target_device_context: cpu
report:
  type: MarkdownReport
  parameters:
    measurements: ./build/yolov4-tvm.json
    report_path: ./build/yolo-report/yolov4-tvm.md
    report_name: YOLOv4 TVM report
    root_dir: ./build/yolo-report
    img_dir: ./build/yolo-report/imgs