# This scenario demonstrates deployment of Anomaly Detection in time series on MAX32960 Evaluation Kit
# It provides two variants of execution - a deployment on an actual hardware, and simulation in Renode
# This scenario should be executed within kenning-zephyr-runtime project, with built evaluation app for
# TFLite Micro runtime:
#
# west build -p always -b max32690evkit/max32690/m4 app -- -DEXTRA_CONF_FILE="tflite.conf"
platform:
  type: LocalPlatform

# model wrapper for the VAE anomaly detection model
model_wrapper:
  type: PyTorchAnomalyDetectionVAE
  parameters:
    model_path: ../vae_cats.pth
    encoder_neuron_list: [16, 8]
    batch_norm: true

# A dataset used for evaluating the model
dataset:
  type: AnomalyDetectionDataset
  parameters:
    dataset_root: ./workspace/dataset
    csv_file: https://zenodo.org/records/8338435/files/data.csv
    split_fraction_test: 0.0005
    inference_batch_size: 1
    split_seed: 12345

# run TFLite conversion from above PyTorch model to TFLite Flatbuffers
optimizers:
  - type: TFLiteCompiler
    parameters:
      target: default
      compiled_model_path: ./workspace/vae_cats.tflite
      inference_input_type: float32
      inference_output_type: float32

report:
  measurements: ./workspace/workspace/vae-tflite-renode.json
  report_path: reports/vae-tflite-renode/report.md
  report_types: [performance,classification]
  to_html: true