# Copyright (c) 2026 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

"""
The module contains a monkey patch for onnx2tf's
``download_test_image_data``. This is a fix to the changed
made in https://github.com/PINTO0309/onnx2tf/issues/921.
"""

import io
from pathlib import Path

import numpy as np


def download_test_image_data() -> np.ndarray:
    """Download dummy data for testing.
    The data is generated by the script located at
    `kenning/temporary_fixes/gen_test_data.py`.

    Returns
    -------
    np.ndarray
        test_image_data
    """
    test_data_file = "sample-calibration-20x128x128x3.npy"
    temp_fixes_dir = Path(__file__).parent.resolve()
    test_data_file = temp_fixes_dir / "resources" / test_data_file

    with open(test_data_file, "rb") as test_sample_images_npy_file:
        test_sample_images_npy = test_sample_images_npy_file.read()
    test_image_data = None
    with io.BytesIO(test_sample_images_npy) as f:
        test_image_data: np.ndarray = np.load(f)
    return test_image_data
