# Copyright (c) 2026 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools>=83", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kenning_llm"
version = "0.0.1"
description = "LLM support for kenning"
authors = [
    {name = "Antmicro Ltd.", email = "contact@antmicro.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "transformers>=5.0.0",  # version fixed for sparsegpt+gptq optimization
    "rouge-score",
    "peft==0.10.0",
    "protobuf>=7.34.0",
    "torch==2.11.0",
    "vllm==0.24.0",
    "safetensors",
]

[project.optional-dependencies]
sparsity-aware-kernel = [
    "kenning_sparsity_aware_kernel @ file:///${PROJECT_ROOT}/kenning/sparsity_aware_kernel",
]